### PR TITLE
Tweak v-alert colours

### PR DESCRIPTION
**Pull request by timothyjohn2015**
Just some minor tweaks to address Andrews feedback:
Screen Shot 2020-09-16 at 4 54 24 PM

### CODE REVIEW

**Comment by AaronThornton00** [comment]
Hey bol, where does this presets folder live?

**Review by Rob-Bee-Neilson — APPROVED** [review]
LGTM
I like it

**Comment by timothyjohn2015** [comment]
> Hey bol, where does this preset folder live?

It's a separate repo, you need to clone it

**Review by sandemchad — APPROVED** [review]
👍 LGTM nice work

**Pull request merged**
