### PR TITLE
Add white-space-pre-wrap class to preset

### PR DESCRIPTION
**Pull request by sandemchad**
- Added `white-space-pre-wrap` for the review answers to wrap properly

### CODE REVIEW

**Review by timothyjohn2015 — CHANGES_REQUESTED** [review]
Could we move these to:

@import "./util_classes";

And move all that .v-application--is-ltr stuff to a well named overrides file?

**Comment by sandemchad** [comment]
@timothyjohn2015 Done here 77fa99f

```
- Renamed some of the existing partials to use the _ partial pattern.
- Created a component_overrides folder for storing scss override partials based on the component name being overriden
- Moved the tab and list overrides into their own partials
- Added a _helper_classes partial for adding any small css helpers we might want that vuetify doesnt currently provide to us.
```

**Review by timothyjohn2015 — CHANGES_REQUESTED** [review]
LGTM Nice one

**Comment by sandemchad** [comment]
@timothyjohn2015 Are there more changes requested? It looks like you might have accidentally clicked request changes instead of approved 😄

**Review by timothyjohn2015 — APPROVED** [review]
LOL whoops

**Comment by timothyjohn2015** [comment]
Feel free to merge!

**Pull request merged**
